# Generated by Django 3.1.3 on 2020-11-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0002_auto_20201102_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='msg',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
