# Generated by Django 3.1.3 on 2020-11-02 16:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0003_auto_20201102_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='msg',
            field=ckeditor.fields.RichTextField(verbose_name='پیام'),
        ),
    ]
