# Generated by Django 3.1.3 on 2020-11-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartproduct', to='Eshop_Product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نمودار محصول',
                'verbose_name_plural': 'نمودار محصولات',
            },
        ),
    ]
