# Generated by Django 3.1.3 on 2020-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0004_auto_20201106_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timeStamp',
            field=models.DateTimeField(verbose_name='زمان ثبت'),
        ),
    ]
