# Generated by Django 3.1.3 on 2020-11-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0005_auto_20201106_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
