# Generated by Django 3.1.3 on 2020-11-07 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0006_auto_20201107_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 17, 20, 5, 888411, tzinfo=utc), verbose_name='زمان ثبت'),
        ),
    ]
