# Generated by Django 3.1.3 on 2020-11-02 09:29

import Eshop_Other.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام برند')),
                ('image', models.ImageField(upload_to=Eshop_Other.models.upload_image_path_brand, verbose_name='برند')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=False, verbose_name='نمایش / روح')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=225, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوای ایمیل')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Eshop_Other.models.upload_image_path, verbose_name='تصویر')),
                ('url', models.URLField(verbose_name='لینک')),
                ('message', models.CharField(max_length=200, verbose_name='پیام')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('notification', ckeditor.fields.RichTextField(verbose_name='متن اعلان')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک مربوطه')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / روح')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
        migrations.CreateModel(
            name='Send_Notifications_email_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeSend', models.BooleanField(default=True, verbose_name='ارسال ایمیل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ایمیل اعلان',
                'verbose_name_plural': 'ایمیل اعلانات',
            },
        ),
    ]
