# Generated by Django 3.1.3 on 2020-11-02 09:29

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('subject', models.CharField(max_length=100, verbose_name='عنوان پیام')),
                ('msg', ckeditor.fields.RichTextField(verbose_name='متن پیام کاربر')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'پیام کاربران',
                'verbose_name_plural': 'پیام های کاربران',
            },
        ),
        migrations.CreateModel(
            name='OpinionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری')),
                ('opinion', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='نظر / انتقاد / پیشنهاد کاربر')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نظر / انتقاد / پیشنهاد',
                'verbose_name_plural': 'نظرات / انتقادات / پیشنهادات',
            },
        ),
    ]
