# Generated by Django 3.1.3 on 2020-11-02 09:29

import Eshop_Auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSpam_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('imageErr', models.ImageField(upload_to=Eshop_Auth.models.upload_image_path_ImageErrSpam, verbose_name='تصویر خطا')),
                ('subject', models.CharField(max_length=100, verbose_name='عنوان خطا')),
                ('msg', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'گزارش خطا',
                'verbose_name_plural': 'گزارش خطاها',
            },
        ),
        migrations.CreateModel(
            name='UltraProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to=Eshop_Auth.models.upload_image_path_profile, verbose_name='تصویر پروفایل')),
                ('phone', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='شماره تماس')),
                ('webName', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس وبسایت')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک پروفایل')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
