# Generated by Django 3.1.3 on 2020-11-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Auth', '0004_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
