# Generated by Django 3.1.3 on 2020-11-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Auth', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
