# Generated by Django 3.1.3 on 2020-11-02 09:29

import Eshop_AboutUs.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فروشگاه')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to=Eshop_AboutUs.models.upload_image_path_LoGo, verbose_name='لوگوی وبسایت')),
                ('Email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('fax', models.IntegerField(verbose_name='فکس')),
                ('Telegram', models.CharField(max_length=100, verbose_name='تلگرام')),
                ('Whatsup', models.BigIntegerField(verbose_name='شماره ی واتس آپ')),
                ('Youtube', models.CharField(max_length=100, verbose_name='یوتیوب')),
                ('Instagram', models.CharField(max_length=100, verbose_name='اینستاگرام')),
                ('Phone_Number', models.BigIntegerField(verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('AboutUs', ckeditor.fields.RichTextField(verbose_name='توضیحاتی درباره ی سایت')),
                ('X_inTheWorld', models.FloatField(blank=True, default=0, null=True, verbose_name='مختصات X در نقشه')),
                ('Y_inTheWorld', models.FloatField(blank=True, default=0, null=True, verbose_name='مختصات Y در نقشه')),
            ],
            options={
                'verbose_name': 'درباره ی ما',
                'verbose_name_plural': 'تنظیمات درباره ی ما',
            },
        ),
    ]
