# Generated by Django 3.1.3 on 2020-11-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eshop_Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offcode', models.CharField(blank=True, max_length=225, null=True, verbose_name='کد تخفیف')),
                ('many', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تسویه')),
                ('paymentDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('ref_Id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کد پیگیری')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک سبد خرید')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد محصول')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت محصول')),
                ('productColor', models.CharField(blank=True, max_length=120, null=True, verbose_name='رنگ محصول')),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Eshop_Order.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Eshop_Product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سبد خرید',
                'verbose_name_plural': 'جزئیات سبد های خرید',
            },
        ),
    ]
